# Generated by Django 3.2.2 on 2021-05-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cldr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
                ('open', models.TextField(blank=True, db_column='Open', null=True)),
                ('high', models.TextField(blank=True, db_column='High', null=True)),
                ('low', models.TextField(blank=True, db_column='Low', null=True)),
                ('close', models.TextField(blank=True, db_column='Close', null=True)),
                ('adjclose', models.TextField(blank=True, db_column='AdjClose', null=True)),
                ('volume', models.TextField(blank=True, db_column='Volume', null=True)),
            ],
            options={
                'db_table': 'CLDR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
                ('open', models.TextField(blank=True, db_column='Open', null=True)),
                ('high', models.TextField(blank=True, db_column='High', null=True)),
                ('low', models.TextField(blank=True, db_column='Low', null=True)),
                ('close', models.TextField(blank=True, db_column='Close', null=True)),
                ('adjclose', models.TextField(blank=True, db_column='AdjClose', null=True)),
                ('volume', models.TextField(blank=True, db_column='Volume', null=True)),
            ],
            options={
                'db_table': 'DOCU',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
                ('open', models.TextField(blank=True, db_column='Open', null=True)),
                ('high', models.TextField(blank=True, db_column='High', null=True)),
                ('low', models.TextField(blank=True, db_column='Low', null=True)),
                ('close', models.TextField(blank=True, db_column='Close', null=True)),
                ('adjclose', models.TextField(blank=True, db_column='AdjClose', null=True)),
                ('volume', models.TextField(blank=True, db_column='Volume', null=True)),
            ],
            options={
                'db_table': 'PD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
                ('open', models.TextField(blank=True, db_column='Open', null=True)),
                ('high', models.TextField(blank=True, db_column='High', null=True)),
                ('low', models.TextField(blank=True, db_column='Low', null=True)),
                ('close', models.TextField(blank=True, db_column='Close', null=True)),
                ('adjclose', models.TextField(blank=True, db_column='AdjClose', null=True)),
                ('volume', models.TextField(blank=True, db_column='Volume', null=True)),
            ],
            options={
                'db_table': 'PINS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
                ('open', models.TextField(blank=True, db_column='Open', null=True)),
                ('high', models.TextField(blank=True, db_column='High', null=True)),
                ('low', models.TextField(blank=True, db_column='Low', null=True)),
                ('close', models.TextField(blank=True, db_column='Close', null=True)),
                ('adjclose', models.TextField(blank=True, db_column='AdjClose', null=True)),
                ('volume', models.TextField(blank=True, db_column='Volume', null=True)),
            ],
            options={
                'db_table': 'RUN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
                ('open', models.TextField(blank=True, db_column='Open', null=True)),
                ('high', models.TextField(blank=True, db_column='High', null=True)),
                ('low', models.TextField(blank=True, db_column='Low', null=True)),
                ('close', models.TextField(blank=True, db_column='Close', null=True)),
                ('adjclose', models.TextField(blank=True, db_column='AdjClose', null=True)),
                ('volume', models.TextField(blank=True, db_column='Volume', null=True)),
            ],
            options={
                'db_table': 'ZM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
                ('open', models.TextField(blank=True, db_column='Open', null=True)),
                ('high', models.TextField(blank=True, db_column='High', null=True)),
                ('low', models.TextField(blank=True, db_column='Low', null=True)),
                ('close', models.TextField(blank=True, db_column='Close', null=True)),
                ('adjclose', models.TextField(blank=True, db_column='AdjClose', null=True)),
                ('volume', models.TextField(blank=True, db_column='Volume', null=True)),
            ],
            options={
                'db_table': 'ZUO',
                'managed': False,
            },
        ),
    ]
