# Generated by Django 3.2.2 on 2021-05-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cldr',
            options={'managed': False, 'verbose_name_plural': 'CLDR'},
        ),
    ]
